@{{
GridRender::setGridId("BookGrid")
  ->enablefilterToolbar()
  ->setGridOption('url',URL::to('/books-grid'))
  ->setGridOption('editurl',URL::to('/crud'))
  ->setGridOption('rowNum', 10)
  ->setGridOption('rownumbers', true)
  ->setGridOption('width', 750)
  ->setGridOption('height', 225)
  ->setGridOption('rowList',array(10,20,30))
  ->setGridOption('caption','Books')
  ->setGridOption('viewrecords',true)
  ->setNavigatorOptions('navigator', array('add' => true, 'edit' => true, 'del' => true, 'view' => true, 'refresh' => false))
  ->setNavigatorOptions('add', array('closeAfterAdd' => true))
  ->setNavigatorEvent('add', 'afterSubmit', 'afterSubmitEvent')
  ->setNavigatorOptions('edit', array('closeAfterEdit' => true))
  ->setNavigatorEvent('edit', 'afterSubmit', 'afterSubmitEvent')
  ->setNavigatorEvent('del', 'afterSubmit', 'afterSubmitEvent')
  ->addColumn(array('index' => 'id', 'hidden' => true, 'editable' => true))
  ->addColumn(array('label' => 'Name', 'index'=>'name', 'editable' => true, 'editrules' => array('required' => true)))
  ->addColumn(array('label' => 'Description','index' => 'description', 'editable' => true, 'edittype' => 'textarea'))
  ->addColumn(array('label' => 'Author','index' => 'author', 'editable' => true, 'editrules' => array('required' => true)))
  ->addColumn(array('label' => 'Publisher','index' => 'publisher', 'editable' => true, 'editrules' => array('required' => true)))
  ->addColumn(array('label' => 'Language','index' => 'language', 'align' => 'center', 'width' => 90, 'editable' => true, 'editoptions' => array('value' => 'E:English;S:Spanish;G:German'), 'edittype' => 'select', 'formatter' => 'select', 'editrules' => array('required' => true)))
  ->addColumn(array('label' => 'Print Length', 'index' => 'length', 'align' => 'center', 'width' => 90, 'editable' => true, 'formatter' => 'integer', 'editrules' => array('required' => true, 'integer' => true)))
  ->addColumn(array('label' => 'ASIN', 'index' => 'asin', 'align' => 'center', 'width' => 105, 'editable' => true, 'editrules' => array('required' => true)))
  ->addGroupHeader(array('startColumnName' => 'name', 'numberOfColumns' => 2, 'titleText' => 'Book Information'))
  ->renderGrid()
}}
